### ISSUE TITLE
BadExpr when rewriting to a non-builtin type

### ISSUE THREAD

**Issue by maverickwoo** [taylorchu/generic#4]
Hi, I have two files in an otherwise-empty `$GOPATH`:
```
src/generic/client/client.go
src/generic/container/container.go
```
with `client.go` being:
```go
//go:generate generic generic/container result TypePayload->generic/client:client.Payload

package client

type Payload struct {
	x, y, z float32
}
```
and `container.go` being:
```go
package container

type TypePayload struct {
	x int
}

type Node struct {
	TypePayload
	name string
}

func (n *Node) SetName(s string) {
	n.name = s
}
```

When I run `go generate` inside `src/generic/client`, I get:
```
package result

import "generic/client"

type client BadExpr

type Node struct {
	client.Payload
	name	string
}

func (n *Node) SetName(s string) {
	n.name = s
}
5:12: expected type, found '.'
client.go:1: running "generic": exit status 1
```

What would be the correct way to specify the rewrite target in the `go:generate` line so as to eliminate the`BadExpr`? Thanks!

**Comment by taylorchu** [comment]
Please use `type TypePayload string`. The placeholder type should be a simple identifier like `string`, `uint32`, `int`, ...etc. Having struct here does not make sense because if it is a placeholder then the generic package implementation should not depend on/access its fields.

generic actually reserves this case for users who simply want to rename `TypePayload` to some other identifiers.

I hope this helps.

**Comment by maverickwoo** [comment]
OK. Declaring `TypePayload` with a simple mock type solves my problem. Thanks for the great work!

P.S. My thinking was that if it is a placeholder than I should be able to use any mock type. I did make sure `container.go` does not touch `x` when I was writing the minimal toy example. :)
